'use strict';
const http=require('http');
const crypto=require('crypto');
const fs=require('fs');
const path=require('path');
const {normalize:normalizeEconomy,snapshot:economySnapshot,applyTransaction}=require('./economy-ledger');
const PORT=Number(process.env.PORT||10001),BOT_TOKEN=String(process.env.TELEGRAM_BOT_TOKEN||'');
const DB_FILE=process.env.TERRITORY_DB_FILE||path.join(__dirname,'data','players.json');
const ORIGINS=String(process.env.CORS_ORIGINS||'*').split(',').map(x=>x.trim()).filter(Boolean);
function nowIso(){return new Date().toISOString()} function load(){try{return JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}catch(_){return{version:5,players:{}}}} function save(db){fs.mkdirSync(path.dirname(DB_FILE),{recursive:true});const t=DB_FILE+'.tmp';fs.writeFileSync(t,JSON.stringify(db,null,2));fs.renameSync(t,DB_FILE)}
const db=load();db.version=Math.max(6,Number(db.version)||1);db.players=db.players&&typeof db.players==='object'?db.players:{};
function cors(req,res){const o=req.headers.origin;if(ORIGINS.includes('*')||ORIGINS.includes(o))res.setHeader('Access-Control-Allow-Origin',ORIGINS.includes('*')?'*':(o||''));res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','content-type,x-telegram-init-data');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS')}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(data))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>500000)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});req.on('error',reject)})}
function validateInitData(raw){if(!raw||!BOT_TOKEN)throw new Error('Telegram auth is not configured');const p=new URLSearchParams(raw),hash=p.get('hash'),authDate=Number(p.get('auth_date')||0);if(!hash||!authDate)throw new Error('Invalid Telegram initData');if(Math.abs(Date.now()/1000-authDate)>86400)throw new Error('Telegram initData expired');const d=[...p.entries()].filter(([k])=>k!=='hash').sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');const secret=crypto.createHmac('sha256','WebAppData').update(BOT_TOKEN).digest(),expected=crypto.createHmac('sha256',secret).update(d).digest('hex');if(expected.length!==hash.length||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(hash)))throw new Error('Telegram signature mismatch');let user;try{user=JSON.parse(p.get('user')||'{}')}catch(_){throw new Error('Invalid Telegram user payload')}if(!user.id)throw new Error('Telegram user missing');return user}
function auth(req){return validateInitData(String(req.headers['x-telegram-init-data']||''))}
function xpNext(level){const l=Math.max(1,Number(level)||1);return Math.max(100,Math.round(90+12*Math.pow(l,1.5)))}
function num(v,min,max,f){const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):f} function str(v,max,f=''){return typeof v==='string'?v.slice(0,max):f} function plain(v){return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}
function safeItem(item){if(!item||typeof item!=='object'||Array.isArray(item))return null;const o={},keys=['id','name','title','slot','type','icon','emoji','rarity','quality','tier','level','enhance','attack','strength','damage','atk','defense','def','armor','guard','agility','agi','speed','maxHp','hp','health','critChance','damageReduction','bonusXp','setId','setName','source'];for(const k of keys){const v=item[k];if(typeof v==='string')o[k]=v.slice(0,160);else if(typeof v==='number'&&Number.isFinite(v))o[k]=num(v,-1000000,1000000,0)}return o}
function safeState(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))return null;const s={level:Math.floor(num(raw.level,1,240,1)),xp:Math.floor(num(raw.xp,0,1000000000,0)),xpNext:Math.floor(num(raw.xpNext,1,1000000000,100)),hp:Math.floor(num(raw.hp,0,1000000,100)),maxHp:Math.floor(num(raw.maxHp,1,1000000,100)),energy:Math.floor(num(raw.energy,0,1000000,100)),maxEnergy:Math.floor(num(raw.maxEnergy,1,1000000,100)),battleStones:Math.floor(num(raw.battleStones,0,1000000,30)),battleStonesBonus:Math.floor(num(raw.battleStonesBonus,0,1000000,0)),battleStonesDate:str(raw.battleStonesDate,32,''),battleStonesCap:Math.floor(num(raw.battleStonesCap,1,1000,30)),equipment:Array.isArray(raw.equipment)?raw.equipment.slice(0,7).map(safeItem):Array(7).fill(null),inventoryItems:Array.isArray(raw.inventoryItems)?raw.inventoryItems.slice(0,100).map(safeItem).filter(Boolean):[],followers:plain(raw.followers),activeFollower:raw.activeFollower==null?null:str(String(raw.activeFollower),80,null),consumables:plain(raw.consumables),pve:plain(raw.pve),currentChapter:Math.floor(num(raw.currentChapter,1,240,1)),chapterStage:Math.floor(num(raw.chapterStage,1,4,1)),chapterProgress:Math.floor(num(raw.chapterProgress,0,100,0)),chapterBossUnlocked:Boolean(raw.chapterBossUnlocked),chapterBossDefeated:Boolean(raw.chapterBossDefeated),chapterCompleted:Boolean(raw.chapterCompleted),forge:plain(raw.forge),arena:plain(raw.arena),daily:plain(raw.daily),weekly:plain(raw.weekly),story:plain(raw.story),auto:Boolean(raw.auto),pos:Math.floor(num(raw.pos,0,100000,0)),dice:Math.floor(num(raw.dice,0,100000,0))};
 s.pve={chapter:Math.floor(num(s.pve.chapter,1,240,s.currentChapter)),stage:Math.floor(num(s.pve.stage,1,4,s.chapterStage)),progress:Math.floor(num(s.pve.progress,0,100,s.chapterProgress)),bossPending:Boolean(s.pve.bossPending||s.chapterBossUnlocked),bossActive:Boolean(s.pve.bossActive),bossDefeated:Math.floor(num(s.pve.bossDefeated,0,1000000,0)),wins:Math.floor(num(s.pve.wins,0,1000000,0))};s.forge={materials:Math.floor(num(s.forge.materials,0,100000000,0)),selectedId:s.forge.selectedId==null?null:str(String(s.forge.selectedId),120,null),successes:Math.floor(num(s.forge.successes,0,1000000,0)),failStreak:Math.floor(num(s.forge.failStreak,0,1000000,0))};s.consumables={};for(const[k,v]of Object.entries(plain(raw.consumables))){if(Object.keys(s.consumables).length>=32)break;s.consumables[str(k,80)]=Math.floor(num(v,0,100000,0))}return s}
function defaultPlayer(user){const ts=nowIso();return{schema_version:6,telegram_id:String(user.id),first_name:str(user.first_name,120),last_name:str(user.last_name,120),username:str(user.username,120),photo_url:str(user.photo_url,1000),level:1,xp:0,xp_next:100,hp:100,max_hp:100,economy:{coins:0,gems:0,red_gems:0,vip:0,economy_version:1,ledger:[],receipts:{}},state:null,legacy_imported:false,created_at:ts,updated_at:ts}}
function playerFor(user){const id=String(user.id);let p=db.players[id];if(!p){p=defaultPlayer(user);db.players[id]=p;save(db);return p}p.schema_version=Math.max(6,Number(p.schema_version)||1);p.first_name=str(user.first_name,120,p.first_name||'');p.last_name=str(user.last_name,120,p.last_name||'');p.username=str(user.username,120,p.username||'');p.photo_url=str(user.photo_url,1000,p.photo_url||'');p.economy=normalizeEconomy(p.economy||{});p.updated_at=nowIso();save(db);return p}
function publicPlayer(p){const e=p.economy||{};return{schema_version:6,first_name:p.first_name||'',last_name:p.last_name||'',username:p.username||'',photo_url:p.photo_url||'',level:num(p.level,1,240,1),xp:num(p.xp,0,1000000000,0),xp_next:num(p.xp_next,1,1000000000,100),hp:num(p.hp,0,1000000,100),max_hp:num(p.max_hp,1,1000000,100),coins:num(e.coins,0,100000000000,0),gems:num(e.gems,0,1000000000,0),red_gems:num(e.red_gems,0,1000000000,0),vip:num(e.vip,0,100,0),has_server_progress:Boolean(p.state||p.legacy_imported||p.level>1||p.xp>0),legacy_imported:Boolean(p.legacy_imported),updated_at:p.updated_at}}
function migrate(p,data){if(p.legacy_imported||p.state||p.level>1||p.xp>0||(p.economy&&(p.economy.coins||p.economy.gems||p.economy.red_gems)))throw new Error('Legacy migration is already closed for this player');const state=safeState(data&&data.state);if(!state)throw new Error('Invalid legacy state');p.level=state.level;p.xp=Math.min(state.xp,xpNext(state.level)-1);p.xp_next=xpNext(state.level);p.hp=state.hp;p.max_hp=state.maxHp;p.state=state;p.legacy_imported=true;p.updated_at=nowIso();save(db)}
const SERVER_OWNED=['pve','currentChapter','chapterStage','chapterProgress','chapterBossUnlocked','chapterBossDefeated','chapterCompleted','battleStones','battleStonesBonus','battleStonesDate','battleStonesCap','level','xp','xpNext','inventoryItems','lootFound','forge','totalChaptersCompleted','chapterRewardsClaimed'];
function syncState(p,raw){const state=safeState(raw);if(!state)throw new Error('Invalid state');const prev=p.state||{};for(const k of SERVER_OWNED)if(prev[k]!==undefined)state[k]=prev[k];p.state=state;p.level=state.level;p.xp=Math.min(state.xp,xpNext(state.level)-1);p.xp_next=xpNext(state.level);p.hp=state.hp;p.max_hp=state.maxHp;p.updated_at=nowIso();save(db);return state}
function equipmentBonusServer(s){const eq=Array.isArray(s.equipment)?s.equipment.slice(0,7):[];let strength=0,defense=0,agility=0,maxHp=0,critChance=0,damageReduction=0,bonusXp=0;const sets={};for(const item of eq){if(!item)continue;const n=(keys)=>{for(const k of keys){const v=Number(item[k]);if(Number.isFinite(v)&&v)return v}return 0};strength+=n(['strength','attack','damage','atk']);defense+=n(['defense','def','armor','guard']);agility+=n(['agility','agi','speed']);maxHp+=n(['maxHp','hp','health']);critChance+=Number(item.critChance)||0;damageReduction+=Number(item.damageReduction)||0;bonusXp+=Number(item.bonusXp)||0;const sid=String(item.setId||'').toLowerCase();if(sid)sets[sid]=(sets[sid]||0)+1}const bonus={strength:0,defense:0,agility:0,maxHp:0,critChance:0,damageReduction:0,bonusXp:0};const rules={tide:[[2,{agility:4}],[4,{strength:10}],[6,{bonusXp:8}]],gold:[[2,{defense:6}],[4,{maxHp:80}],[6,{damageReduction:8}]],blackflag:[[2,{strength:7}],[4,{agility:7}],[6,{critChance:8}]],sacred:[[2,{defense:8}],[4,{strength:12}],[6,{maxHp:120}]],warchief:[[2,{strength:15}],[4,{defense:15}],[6,{critChance:12}]]};for(const [id,count] of Object.entries(sets))for(const [need,vals] of (rules[id]||[]))if(count>=need)for(const [k,v] of Object.entries(vals))bonus[k]+=v;return{strength:strength+bonus.strength,defense:defense+bonus.defense,agility:agility+bonus.agility,maxHp:maxHp+bonus.maxHp,critChance:critChance+bonus.critChance,damageReduction:damageReduction+bonus.damageReduction,bonusXp:bonusXp+bonus.bonusXp}}
function followerServer(s){const id=s.followers?.activeFollower??s.activeFollower;if(!id)return null;if(typeof id==='object')return{id:id.id||'',effect:id.effect||'guard'};const map={liabro:'crit',teralel:'guard','king-cow':'heal',mort:'dodge',stone:'control'};return{id:String(id),effect:map[String(id)]||'guard'}}
function rngNext(hex){let x=Number.parseInt(String(hex||'0').slice(0,8),16)>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;return{x:(x>>>0).toString(16).padStart(8,'0'),value:(x>>>0)/4294967296}}
function initCombat(p,chapter,stage,boss){const s=p.state||{},e=equipmentBonusServer(s),f=followerServer(s),level=Math.max(1,Number(s.level)||1),strength=125+level*2+e.strength,defense=98+level+e.defense,agility=101+level+e.agility,maxHp=Math.max(1,(Number(s.maxHp)||100)+e.maxHp);const base=boss?{hp:2600,damage:26}:{hp:[1100,1250,1400,1600][Math.max(1,Math.min(4,stage))-1],damage:[12,14,16,18][Math.max(1,Math.min(4,stage))-1]};const scale=1+(chapter-1)*0.055;const enemyHp=boss?2600:Math.round(base.hp*scale);const enemyDamage=boss?26:Math.max(1,Math.round(base.damage*(1+(chapter-1)*0.035)));return{seed:crypto.randomBytes(16).toString('hex'),heroHp:Math.max(1,Number(s.hp)||maxHp),maxHp,enemyHp,enemyMaxHp:enemyHp,enemyDamage,damage:Math.max(boss?24:20,Math.floor(strength/(boss?4:5))),strength,defense,agility,critChance:e.critChance,follower:f?.effect||null,turn:0,mp:0,skillCooldownUntil:0,incomingReduction:0,startedAt:Date.now(),bossTime:boss?20:null,ended:false,result:null}}
function combatRand(c){const r=rngNext(c.seed);c.seed=r.x;return r.value}
function combatAction(session,action){const c=session.combat;if(!c||c.ended)throw new Error('Battle is already finished');const now=Date.now();if(now-c.startedAt>30*60*1000)throw new Error('Battle session expired');if(c.boss&&false){};const a=String(action||'');if(/^skill:/.test(a)&&now<c.skillCooldownUntil)throw new Error('Skill is on cooldown');if((a==='attack'||a==='skill:power'||a==='skill:fire'||a==='skill:guard'||a==='skill:burst'||a==='skill:crown')&&now-c.startedAt<0)throw new Error('Invalid battle clock');
if(a==='elixir_hp')c.heroHp=Math.min(c.maxHp,c.heroHp+30);else if(a==='elixir_energy'){}else if(a==='elixir_attack')c.damage+=5;else if(a==='elixir_guard')c.incomingReduction=Math.min(.55,c.incomingReduction+.08);else{let dmg=0;if(a==='attack'||a==='skill:power'){dmg=c.damage+Math.floor(combatRand(c)*Math.max(5,Math.floor(c.agility/20)));if((c.follower==='crit'&&combatRand(c)<.22)||combatRand(c)<Math.min(.75,c.critChance/100))dmg=Math.floor(dmg*1.7);if(c.follower&&c.turn%3===0)dmg+=6+Math.floor(c.agility/18);if(a==='skill:power'){dmg=Math.floor(dmg*1.8);c.mp=Math.min(100,c.mp+8);c.skillCooldownUntil=now+2000}else c.mp=Math.min(100,c.mp+12)}else if(a==='skill:fire'){dmg=Math.floor(c.damage*1.45);c.skillCooldownUntil=now+2000}else if(a==='skill:burst'){c.mp=Math.min(100,c.mp+25);c.damage+=4;dmg=0}else if(a==='skill:guard'){c.heroHp=Math.min(c.maxHp,c.heroHp+Math.floor(c.maxHp*.12));c.skillCooldownUntil=now+2000;dmg=0}else if(a==='skill:crown'){c.heroHp=Math.min(c.maxHp,c.heroHp+Math.floor(c.maxHp*.2));c.skillCooldownUntil=now+3000;dmg=0}else throw new Error('Invalid battle action');c.enemyHp=Math.max(0,c.enemyHp-dmg);c.turn++;
if(c.enemyHp<=0){c.ended=true;c.result='win';return snapshotCombat(c)}let incoming=c.enemyDamage+Math.floor(combatRand(c)*6);if(c.follower==='guard')incoming=Math.max(1,Math.floor(incoming*.78));if(c.incomingReduction)incoming=Math.max(1,Math.floor(incoming*(1-c.incomingReduction)));if(c.follower==='dodge'&&combatRand(c)<.18)incoming=0;if(c.follower==='heal'&&c.turn%3===0)c.heroHp=Math.min(c.maxHp,c.heroHp+Math.floor(c.maxHp*.08));c.heroHp=Math.max(0,c.heroHp-incoming);if(c.heroHp<=0){c.ended=true;c.result='lose'} }
if(c.bossTime!==null)c.bossTime=Math.max(0,20-Math.floor((now-c.startedAt)/1000));if(c.bossTime===0&&!c.ended){c.ended=true;c.result='lose'}return snapshotCombat(c)}
function snapshotCombat(c){return{heroHp:Math.round(c.heroHp),maxHp:c.maxHp,enemyHp:Math.round(c.enemyHp),enemyMaxHp:c.enemyMaxHp,turn:c.turn,mp:c.mp,ended:c.ended,result:c.result,bossTime:c.bossTime}}
function battleStoneStart(p,ch,st,boss){
  p.battle_sessions=p.battle_sessions||{};
  if(p.active_battle_session){const active=p.battle_sessions[p.active_battle_session];if(active&&!active.completed&&Date.now()-Number(active.created_at)<30*60*1000)throw new Error('A PvE battle is already active');p.active_battle_session=null;}const s=p.state||{},chapter=Math.max(1,Math.min(240,Number(ch)||1)),stage=Math.max(1,Math.min(4,Number(st)||1));if(chapter!==Math.max(1,Number(s.currentChapter)||1))throw new Error('Chapter mismatch');if(!boss&&stage!==Math.max(1,Number(s.chapterStage)||1))throw new Error('Stage mismatch');if(boss&&!s.chapterBossUnlocked)throw new Error('Boss is not unlocked');const bonus=Math.max(0,Number(s.battleStonesBonus)||0),stones=Math.max(0,Number(s.battleStones)||0);if(bonus<=0&&stones<=0)throw new Error('No battle stones');if(bonus>0)s.battleStones=Number(s.battleStones)||0,s.battleStonesBonus=bonus-1;else s.battleStones=stones-1;p.state=s;p.battle_sessions=p.battle_sessions||{};const id=crypto.randomUUID();p.battle_sessions[id]={id,chapter,stage,boss:!!boss,created_at:Date.now(),completed:false,actions:[],last_action_at:0,nonce:crypto.randomBytes(24).toString('hex'),seed:crypto.randomBytes(16).toString('hex'),combat:initCombat(p,chapter,stage,!!boss)};p.active_battle_session=id;const cutoff=Date.now()-30*60*1000;for(const[k,v]of Object.entries(p.battle_sessions))if(!v||Number(v.created_at)<cutoff||v.completed)delete p.battle_sessions[k];p.updated_at=nowIso();save(db);return{id,state:s,nonce:p.battle_sessions[id].nonce,seed:p.battle_sessions[id].seed,combat:snapshotCombat(p.battle_sessions[id].combat)}}
function gearXp(s){return (Array.isArray(s.equipment)?s.equipment:[]).reduce((n,x)=>n+(Number(x?.bonusXp)||0),0)}
function addXp(p,amount){let s=p.state||{};let xp=Math.max(0,Number(s.xp)||0)+Math.max(0,Math.floor(amount));let level=Math.max(1,Number(s.level)||1);while(level<240&&xp>=xpNext(level)){xp-=xpNext(level);level++}s.level=level;s.xp=xp;s.xpNext=xpNext(level);p.level=level;p.xp=xp;p.xp_next=xpNext(level);return{level,xp,xpNext:s.xpNext}}
function makeLoot(p,chapter,stage,boss){const s=p.state||{},types=[['Оружие','🪓','weapon'],['Шлем','🪖','helmet'],['Доспех','🛡️','armor'],['Пояс','🎗️','belt'],['Сапоги','🥾','boots'],['Кольцо','💍','ring'],['Амулет','🔮','amulet']],idx=(Math.max(1,Number(stage)||1)-1+(boss?2:0))%types.length,[slot,icon,type]=types[idx],rarities=boss?['epic','legendary']:['common','uncommon','rare','epic'],rarity=rarities[crypto.randomInt(0,rarities.length)],names={common:'Старинный',uncommon:'Закалённый',rare:'Воинский',epic:'Героический',legendary:'Легендарный'},power=(Number(stage)||1)*4+(boss?18:crypto.randomInt(0,7)),setIds=boss?['warchief']:['tide','gold','blackflag','sacred'],setNames={tide:'Морской дозор',gold:'Золотой страж',blackflag:'Чёрный флаг',sacred:'Священные врата',warchief:'Вождь племени'},setId=setIds[Math.max(0,Math.min(setIds.length-1,(Number(stage)||1)-1))],affixPool={common:[],uncommon:['crit'],rare:['guard','crit'],epic:['guard','crit','xp'],legendary:['guard','crit','xp']},aff=affixPool[rarity]||[];return{id:`loot_${Date.now()}_${crypto.randomBytes(3).toString('hex')}`,name:`${names[rarity]} ${slot}`,title:`${names[rarity]} ${slot}`,slot,type,icon,rarity,level:Math.max(1,Number(s.level)||1),enhance:0,attack:type==='weapon'?power:0,defense:['armor','helmet','belt','boots'].includes(type)?power:0,agility:['boots','ring'].includes(type)?Math.max(1,Math.floor(power/2)):0,maxHp:type==='armor'?power*3:0,setId,setName:setNames[setId],source:'pve',critChance:aff.includes('crit')?(rarity==='legendary'?4:rarity==='epic'?3:2):0,damageReduction:aff.includes('guard')?(rarity==='legendary'?4:rarity==='epic'?3:2):0,bonusXp:aff.includes('xp')?(rarity==='legendary'?5:3):0}}
function pveAction(p,sessionId,action){
  const session=(p.battle_sessions||{})[String(sessionId||'')];
  if(!session||session.completed)throw new Error('Invalid or completed battle session');
  const age=Date.now()-Number(session.created_at); if(age>30*60*1000)throw new Error('Battle session expired');
  const type=String(action?.type||'').slice(0,24); if(!['basic','power','guard','fire','burst','crown','elixir_hp','elixir_energy','elixir_attack','elixir_guard'].includes(type))throw new Error('Invalid battle action');
  const at=Number(action?.at)||Date.now();
  if(at<Number(session.created_at)-2000||at>Date.now()+2000)throw new Error('Invalid action time');
  if(Number(session.last_action_at)&&at<Number(session.last_action_at))throw new Error('Battle actions out of order');
  if(session.actions.length>=240)throw new Error('Too many battle actions');
  session.actions.push({i:session.actions.length+1,type,at}); session.last_action_at=at; p.updated_at=nowIso(); save(db);
  return {accepted:true,index:session.actions.length};
}
function pveSessionAction(p,sessionId,nonce,action){const session=(p.battle_sessions||{})[String(sessionId||'')];if(!session||session.completed)throw new Error('Invalid battle session');if(String(nonce||'')!==String(session.nonce))throw new Error('Invalid battle nonce');const a=String(action||'');if(!/^(attack|skill:(power|guard|fire|burst|crown)|elixir_(hp|energy|attack|guard))$/.test(a))throw new Error('Invalid battle action');if(Date.now()-Number(session.created_at)>30*60*1000)throw new Error('Battle session expired');if((session.actions||[]).length>=500)throw new Error('Too many battle actions');const result=combatAction(session,a);session.actions=session.actions||[];session.actions.push({action:a,at:Date.now(),state:result});session.last_action_at=Date.now();save(db);return{ok:true,actions:session.actions.length,combat:result}} 
function pveSessionComplete(p,sessionId){const session=(p.battle_sessions||{})[String(sessionId||'')];if(!session||session.completed)throw new Error('Invalid or already completed battle session');const age=Date.now()-Number(session.created_at);if(age>30*60*1000)throw new Error('Battle session expired');const minimumAge=session.boss?5000:1500;const minimumActions=session.boss?3:2;if(Number((session.actions||[]).length)<minimumActions)throw new Error('Battle transcript is incomplete');if(session.combat?.result!=='win')throw new Error('Server has not confirmed the battle victory');if(age<minimumAge)throw new Error('Battle completed too quickly');const s=p.state||{};if(Number(s.currentChapter)!==session.chapter)throw new Error('Battle chapter is no longer current');if(!session.boss&&Number(s.chapterStage)!==session.stage)throw new Error('Battle stage is no longer current');if(session.boss&&!s.chapterBossUnlocked)throw new Error('Boss is no longer available');session.completed=true;if(p.active_battle_session===session.id)p.active_battle_session=null;const chapter=session.chapter,boss=!!session.boss,milestone=boss&&chapter%10===0;const reward=boss?{coins:milestone?1250:500,gems:milestone?25:5,red_gems:0}:{coins:25,gems:0,red_gems:0};const tx=applyTransaction(p,{id:'pve:'+session.id,reason:boss?'pve_boss_reward':'pve_stage_reward',delta:reward},()=>save(db));const xpBase=boss?60:20;const xp=Math.round(xpBase*(1+gearXp(s)/100));addXp(p,xp);const loot=makeLoot(p,chapter,session.stage,boss);s.inventoryItems=Array.isArray(s.inventoryItems)?s.inventoryItems:[];s.inventoryItems.unshift(loot);s.inventoryItems=s.inventoryItems.slice(0,100);s.lootFound=Math.max(0,Number(s.lootFound)||0)+1;if(boss){s.pve=s.pve||{};s.pve.bossActive=false;s.pve.bossPending=false;s.pve.bossDefeated=(Number(s.pve.bossDefeated)||0)+1;s.chapterBossUnlocked=false;s.chapterBossDefeated=true;s.totalChaptersCompleted=Math.max(0,Number(s.totalChaptersCompleted)||0)+1;s.forge=s.forge||{materials:0,selectedId:null,successes:0,failStreak:0};const mat=10+chapter+(milestone?40:0);s.forge.materials=(Number(s.forge.materials)||0)+mat;if(chapter<240){s.currentChapter=chapter+1;s.chapterStage=1;s.chapterProgress=0;s.chapterBossUnlocked=false;s.chapterBossDefeated=false;s.chapterCompleted=false;s.pve.chapter=chapter+1;s.pve.stage=1;s.pve.progress=0;s.pve.bossPending=false;s.pve.bossActive=false}else{s.chapterCompleted=true}}else{s.pve=s.pve||{};s.pve.wins=(Number(s.pve.wins)||0)+1;s.pve.progress=Math.min(100,(Number(s.pve.progress)||0)+25);s.chapterProgress=s.pve.progress;if(s.pve.progress>=100){s.chapterBossUnlocked=true;s.pve.bossPending=true;s.chapterStage=4;s.pve.stage=4}else{s.chapterStage=Math.min(4,Number(s.chapterStage||1)+1);s.pve.stage=s.chapterStage}}p.updated_at=nowIso();save(db);return{reward,economy:tx.economy,state:s,loot,xp}}
const routes=new Set(['/api/auth','/api/player','/api/migrate','/api/progress','/api/state','/api/economy','/api/pve/start','/api/pve/action','/api/pve/complete']);
const server=http.createServer(async(req,res)=>{cors(req,res);if(req.method==='OPTIONS'){res.statusCode=204;return res.end()}try{const u=new URL(req.url,'http://localhost');if(req.method==='GET'&&u.pathname==='/health')return json(res,200,{ok:true,service:'territory-server',version:9,foundation:'SERVER-COMBAT-10STEP'});if(!routes.has(u.pathname))return json(res,404,{error:'Not found'});const user=auth(req),player=playerFor(user);if(req.method==='GET'&&(u.pathname==='/api/auth'||u.pathname==='/api/player'))return json(res,200,{ok:true,player:publicPlayer(player),state:player.state||null});if(req.method==='GET'&&u.pathname==='/api/progress')return json(res,200,{ok:true,player:publicPlayer(player),state:player.state||null});if(req.method==='GET'&&u.pathname==='/api/economy')return json(res,200,{ok:true,economy:economySnapshot(player.economy)});if(req.method==='GET'&&u.pathname==='/api/state')return json(res,200,{ok:true,schema_version:8,state:player.state||null});if(req.method==='POST'&&u.pathname==='/api/migrate'){const d=await body(req);migrate(player,d);return json(res,200,{ok:true,player:publicPlayer(player),state:player.state||null})}if(req.method==='POST'&&u.pathname==='/api/pve/start'){const d=await body(req),x=battleStoneStart(player,d.chapter,d.stage,!!d.boss);return json(res,200,{ok:true,session_id:x.id,state:x.state,player:publicPlayer(player)})}if(req.method==='POST'&&u.pathname==='/api/pve/action'){const d=await body(req),x=pveSessionAction(player,d.session_id,d.nonce,d.action);return json(res,200,x)}if(req.method==='POST'&&u.pathname==='/api/pve/complete'){const d=await body(req),x=pveSessionComplete(player,d.session_id);return json(res,200,{ok:true,reward:x.reward,economy:x.economy,player:publicPlayer(player),state:x.state,loot:x.loot,xp:x.xp})}if(req.method==='POST'&&u.pathname==='/api/state'){const d=await body(req),state=syncState(player,d&&d.state);return json(res,200,{ok:true,schema_version:8,player:publicPlayer(player),state})}return json(res,405,{error:'Method not allowed'})}catch(e){const status=/Telegram|auth|signature|initData|user missing|expired/i.test(e.message||'')?401:400;return json(res,status,{error:e.message||'Request failed'})}});
server.listen(PORT,()=>console.log(`[Territory] server listening on :${PORT} · foundation 10STEP`));
